### ISSUE TITLE
read.csv stringsAsFactors argument now defaults to FALSE? [episode 11]

### ISSUE THREAD

**Issue by HungryWave** [swcarpentry/r-novice-inflammation#402] opened 2018-11-14 21:17 UTC
I am an R newbie. In the reading CSV files chapter, the example of replacing one color name with another does not seem to produce a vector with numbers now. It looks as though read.csv defaults to reading in the colors as strings now. Has this changed? Should this chapter be updated?

**Comment by HungryWave** [comment] 2018-11-14 21:17
# Here we will use R's `ifelse` function, in which we provide the test phrase,
# the outcome if the result of the test is 'TRUE', and the outcome if the
# result is 'FALSE'. We will also assign the results to the Color column,
# using '<-'

# First - reload the data with a header
carSpeeds <- read.csv(file = 'data/car-speeds.csv')

carSpeeds$Color <- ifelse(carSpeeds$Color == 'Blue', 'Green', carSpeeds$Color)
carSpeeds$Color

This does not produce a vector with numbers.

**Comment by diyadas** [comment] 2018-11-15 06:14
Hello @HungryWave! I believe you're referring to [Episode 11](http://swcarpentry.github.io/r-novice-inflammation/11-supp-read-write-csv/index.html).

Thank you for sharing this info. I have a few questions, since I'm not able to reproduce this. If you are willing to provide some additional information, this might help figure out why you are getting a different result:

1. Could you please let us know which version of R you are using? Our latest build of the lesson seems to be on 3.5, as is my local version. 
2. Could you please let me know the result of `options()$stringsAsFactors` for you?

Thanks!

**Comment by diyadas** [comment] 2019-01-18 00:47
Closing as unable to reproduce - please comment with your R version if this still occurring and we'll take a look again.

**Closed by diyadas** 2019-01-18 00:47 UTC
Labels: status:need more info
