### ISSUE TITLE
Permission denied error when rendering Rmarkdown file

### ISSUE THREAD

**Issue by statkclee** [swcarpentry/r-novice-inflammation#399] opened 2018-10-15 00:54 UTC
I'm trying to translate R Novice Rmd file into Korean.
At the final stage for the HTML production, I've got the following error,

`kclee@MacBook:~/swc/r-novice-kr$ sudo make lesson-md`

`make: bin/knit_lessons.sh: Permission denied`
`make: *** [_episodes/01-starting-with-data.md] Error 1`

Is there any walkaround?

**Comment by katrinleinweber** [comment] 2018-10-15 07:12
Hello! This is probably related to our recent clean-up (https://github.com/swcarpentry/r-novice-inflammation/commit/98825367d8ecf555e567cd8538f403f259940313). Does the process not create the `_episodes` folder by itself? Does `mkdir _episodes` and repeating the process prevent this error?

**Comment by katrinleinweber** [comment] 2018-10-15 15:40
It shouldn't be. [`make lesson-md`](https://github.com/swcarpentry/r-novice-inflammation/blob/98825367d8ecf555e567cd8538f403f259940313/Makefile#L88-L92) should just work. I'm on it!

**Comment by katrinleinweber** [comment] 2018-10-15 15:50
OK, I bisected through the history but could not reproduce this problem, at first. It does not seem to be an issue with the code.

Thus, it might be with your copy of `knit_lessons.sh`. Please try the following in a terminal/shell:

1. `ls -lg bin/knit_lessons.sh` -- If the returned permission set is something like `-rw-r--r--` (no `x`!) the file is not marked as e`x`excutable.
2. You can make it so with `chmod +x bin/knit_lessons.sh`.

Both commands assume that you `cd`'ed into the `r-novice-inflammation` root folder. Please try this and let me know whether it runs through then.

**Comment by katrinleinweber** [comment] 2018-10-15 15:56
PS @diyadas: The [Travis failure](https://travis-ci.org/swcarpentry/r-novice-inflammation/builds/441060276#L1706) reported for this repo currently, seems to be different, although the error message contains `01-starting-with-data.md` as well. The site still works, as does the download link from the `files` location (see #398).

I can't investigate this week, so I suggest the not-so-great option of waiting for another commit or PR to trigger Travis again.

**Comment by diyadas** [comment] 2018-10-15 16:33
Thanks for the heads up. I suspect that it does need the` _episodes` folder to be a part of the repo? 

@fmichonneau can you confirm, off-hand?

**Comment by katrinleinweber** [comment] 2018-10-15 17:04
OK, that can be easily tested.

**Comment by katrinleinweber** [comment] 2018-10-15 17:42
As usual, you were rigth :-)

**Comment by statkclee** [comment] 2018-10-16 00:46
@katrinleinweber `chmod` just works. Thank you so much!

**Comment by diyadas** [comment] 2018-10-16 15:34
Great! I'm closing this issue, but do let us know if you continue to have similar problems.

**Closed by diyadas** 2018-10-16 15:34 UTC
Labels: type:template and tools
